blank_issues_enabled: true
contact_links:
  - name: Support
    url: https://tailscale.com/contact/support/
    about: Contact us for support
  - name: Troubleshooting
    url: https://tailscale.com/kb/1023/troubleshooting
    about: Troubleshoot common issues